services:
  srv-estoque:
    container_name: srv-estoque
    image: srv-estoque
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb-estoque
    depends_on:
      - mongodb-estoque
    networks:
      - srv-estoque-network
    volumes:
      - srv-estoque-data:/data/srv-estoque
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - "8082:8082"
    restart: always

  mongodb-estoque:
    image: mongo:latest  # Imagem oficial do mongodb-srv-estoqueDB
    container_name: mongodb-estoque
    ports:
      - "27020:27017"  # Mapeia a porta 27019 do host para a porta 27017 do container
    volumes:
      - mongodb-estoque-data:/data/db  # Volume para persistir os dados do banco de dados
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Defina o nome de usuário root
      - MONGO_INITDB_ROOTs_PASSWORD=rootpass  # Defina a senha para o usuário root
    networks:
      - srv-estoque-network

networks:
  srv-estoque-network:

volumes:
  mongodb-estoque-data:
  srv-estoque-data:
