services:
  estoque:
    container_name: estoque
    image: estoque
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - estoque-network
    volumes:
      - estoque-data:/data/estoque
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - 8083:8083
    restart: always

  mongo:
    image: mongo:latest  # Imagem oficial do MongoDB
    container_name: mongo-container
    ports:
      - "27019:27017"  # Mapeia a porta 27019 do host para a porta 27017 do container
    volumes:
      - mongo-data:/data/db  # Volume para persistir os dados do banco de dados
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Defina o nome de usuário root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass  # Defina a senha para o usuário root
    networks:
      - estoque-network

networks:
  estoque-network:

volumes:
  mongo-data:
  estoque-data:
