spring:
  application:
    name: estoque
  data:
    mongodb:
      host: mongodb-estoque
      database: estoque
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpass}
      authentication-database: admin
server:
  port: 8082
